# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Speakers
    url: '#speaker'
    weight: 20
  - name: About
    url: '#about'
    weight: 10
  - name: Programme
    url: '#programme'
    weight: 30
  - name: Organisers
    url: '#organiser'
    weight: 60
  - name: Partners
    url: '#partners'
    weight: 70
  - name: Registration
    url: 'https://onlineshop.shef.ac.uk/conferences-and-events/faculty-of-engineering/faculty-of-engineering/first-workshop-on-multimodal-ai'
    weight: 80
  - name: Contact Us
    url: '#contact'
    weight: 90
  - name: Blog
    url: 'https://medium.com/@haipinglu/imagine-multimodal-ai-7eb4ef47f2ab'
    weight: 100

