# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Latest Event
    url: '#about'
    weight: 20

  - name: Keynote Speaker
    url: '#speaker'
    weight: 10

  - name: Programme
    url: '#pre-events'
    weight: 30
  #- name: MultimodalAI'23
    #url: multimodalai23
    #weight: 110
  #- name: Registration
    #url: 'https://onlineshop.shef.ac.uk/conferences-and-events/faculty-of-engineering/faculty-of-engineering/first-workshop-on-multimodal-ai'
    #weight: 80

  #- name: Contact Us
    #url: '#contact'
    #weight: 30

  #- name: Direction
    #url: '#direction'
    #weight: 40
  - name: Sponsorship
    url: call_for_sponsorship
    weight: 40

  - name: "Past Events"
    url: '#'
    weight: 60

  - name: "MultimodalAIForum'24"
    parent: "Past Events"  # Parent name must match exactly
    url: multimodalai-forum24
    weight: 1

  - name: "MultimodalAISprint'23"
    parent: "Past Events"  # Parent name must match exactly
    url: multimodalai-sprint23
    weight: 2

  - name: "MultimodalAI'23"
    parent: "Past Events"  # Parent name must match exactly
    url: multimodalai23
    weight: 3

 # - name: "Openings"
    #url: opening
    #weight: 70

